[package]
name = "miracl_core_bls12381"
version = "1.0.0"
documentation = "https://github.com/miracl/core"
repository = "https://github.com/dfinity-publish/miracl_core_bls12381"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

